apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vpa
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vpa
  template:
    metadata:
      labels:
        app: nginx-vpa
    spec:
      containers:
      - name: nginx
        image: nginx
